#include "orderbook.h"
#include <iostream>
#include <chrono>
 
using std::cin;
using std::cout;
 
// Returns the current time in nanoseconds, for timing a single order
// the same way the reference repo's unix_time() does - this is a
// DEMO flourish, not a real benchmark. One sample with terminal I/O
// sitting around it tells you almost nothing statistically reliable.
// The real benchmark harness (separate, tight-loop, no I/O) is what
// the resume bullet's numbers will actually come from.
uint64_t now_ns() {
    return std::chrono::duration_cast<std::chrono::nanoseconds>(
        std::chrono::high_resolution_clock::now().time_since_epoch()
    ).count();
}
 
// Summarizes the trades generated by ONE submission: total quantity
// filled and the quantity-weighted average fill price.
std::pair<uint64_t, double> summarize_fill(const std::vector<trade>& trades, size_t before_count) {
    uint64_t filled_qty = 0;
    double weighted_price_sum = 0.0;
 
    for (size_t i = before_count; i < trades.size(); ++i) {
        filled_qty += trades[i].quantity;
        weighted_price_sum += trades[i].price * trades[i].quantity;
    }
 
    double avg_price = (filled_qty > 0) ? (weighted_price_sum / filled_qty) : 0.0;
    return {filled_qty, avg_price};
}
 
void print_fill(uint64_t filled_qty, double avg_price, uint64_t requested_qty,
                 uint64_t start_ns, uint64_t end_ns) {
    cout << "Filled " << filled_qty << " / " << requested_qty << " units";
    if (filled_qty > 0) {
        cout << " @ avg price $" << avg_price;
    }
    cout << "  (" << (end_ns - start_ns) << "ns)" << ln;
}
 
int main() {
    orderbook ob;
    uint64_t next_order_id = 1;
 
    while (true) {
        int action;
        cout << "Options\n"
             << "--------------------------------\n"
             << "|1. Print Orderbook            |\n"
             << "|2. Submit order                |\n"
             << "|3. Cancel order                |\n"
             << "|4. Exit                        |\n"
             << "--------------------------------\n"
             << "Choice: ";
 
        if (!(cin >> action)) {
            cout << "Invalid input, exiting." << ln;
            break;
        }
        cout << ln;
 
        if (action == 1) {
            ob.printbook();
 
        } else if (action == 2) {
            int order_type_input;
            int side_input;
            uint64_t quantity;
            uint64_t trader_id;
            double price = 0.0;
 
            cout << "Enter order type:\n0. Market order\n1. Limit order\nSelection: ";
            cin >> order_type_input;
 
            cout << ln << "Enter side:\n0. Buy\n1. Sell\nSelection: ";
            cin >> side_input;
            Side side = (side_input == 0) ? Side::Buy : Side::Sell;
 
            cout << ln << "Enter order quantity: ";
            cin >> quantity;
 
            // NOTE: this prompt doesn't exist in the reference repo's
            // version. It's required here because self-trade
            // prevention - which your engine has and theirs does not
            // appear to - needs to know who placed each order.
            cout << ln << "Enter trader id: ";
            cin >> trader_id;
 
            uint64_t id = next_order_id++;
            size_t trades_before = ob.get_trades().size();
            uint64_t start = now_ns();
 
            if (order_type_input == 0) {
                cout << ln << "Submitting market " << (side == Side::Buy ? "buy" : "sell")
                     << " order for " << quantity << " units.." << ln;
                ob.submit_market_order(id, trader_id, side, quantity);
            } else {
                cout << ln << "Enter limit price: ";
                cin >> price;
                cout << ln << "Submitting limit " << (side == Side::Buy ? "buy" : "sell")
                     << " order for " << quantity << " units @ $" << price << ".." << ln;
                ob.submit_limit_order(id, trader_id, side, price, quantity);
            }
 
            uint64_t end = now_ns();
            auto [filled_qty, avg_price] = summarize_fill(ob.get_trades(), trades_before);
            print_fill(filled_qty, avg_price, quantity, start, end);
 
        } else if (action == 3) {
            uint64_t order_id;
            cout << "Enter order id to cancel: ";
            cin >> order_id;
            bool canceled = ob.cancel_order(order_id);
            cout << ln << (canceled ? "Canceled." : "No such order.") << ln;
 
        } else if (action == 4) {
            cout << "Exiting." << ln;
            break;
 
        } else {
            cout << "Invalid choice." << ln;
        }
 
        cout << ln;
    }
 
    return 0;
}
